name: aarch64-test

on: [push]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on alpine aarch64
    steps:
      - uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2.1.0
        name: make test
        id: test
        with:
          arch: aarch64
          distro: fedora_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo 'fastestmirror=1' | tee -a /etc/dnf/dnf.conf
            echo 'check_config_file_age=False' | tee -a /etc/dnf/dnf.conf
            echo 'metadata_expire=-1' | tee -a /etc/dnf/dnf.conf
            dnf -y -q install gcc make
            make test
