name: aarch64-test

on: [push]

jobs:
  test:

    runs-on: fedora-latest
    name: Build and test MIR

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: make test
        with:
          arch: aarch64
          distro: fedora-latest
          githubToken: ${{ github.token }}

          run: |
            uname -a
            make test
