name: AMD64-Linux-bench

on:
  schedule:
    # Run at 22:40 UTC on Thursday
    - cron:  '40 17 * * 4'

jobs:
  bench:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: make bench
      run: make bench
